### ISSUE TITLE
node.js error

### ISSUE THREAD

**Issue by ferzrrn** [PvtTyphoon/lfm-rich-presence#6]
Im try to run this as a node.js script, but get this error:

PS C:\Users\ferzr> node main.js
Type out your last.fm username and then hit enter: ferzrrn
Connecting.
Discord rich presence established.
Discord status updated.
C:\Users\ferzr\node_modules\discord-rpc\src\client.js:178
        const e = new Error(message.data.message);
                  ^

Error: child "activity" fails because [child "assets" fails because [child "large_image" fails because ["large_image" is not allowed to be empty]]]
    at RPCClient._onRpcMessage (C:\Users\ferzr\node_modules\discord-rpc\src\client.js:178:19)
    at IPCTransport.emit (node:events:526:28)
    at C:\Users\ferzr\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\Users\ferzr\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\ferzr\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 4000,
  data: {
    code: 4000,
    message: 'child "activity" fails because [child "assets" fails because [child "large_image" fails because ["large_image" is not allowed to be empty]]]'
  }
}

**Comment by PvtTyphoon** [comment]
Looks like a lastfm api error where the api returns an empty object, situational but I'll add a check for empty return values in the next version
